//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.inscricaos = new HashSet<inscricao>();
        }
    
        public int Id_evento { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public string Descricao { get; set; }
        public string Local_Evento { get; set; }
        public string Agenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscricao> inscricaos { get; set; }
    }
}
