//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscricao
    {
        public int id_inscricao { get; set; }
        public Nullable<System.DateTime> Data_Inscricao { get; set; }
        public Nullable<int> Evento { get; set; }
        public Nullable<int> Participantes { get; set; }
    
        public virtual evento evento1 { get; set; }
        public virtual participante participante { get; set; }
    }
}
