//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawDK
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participante()
        {
            this.inscricaos = new HashSet<inscricao>();
        }
    
        public int Id_participantes { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public Nullable<int> Grau_academico { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.DateTime> Data_nascimento { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Telefone { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscricao> inscricaos { get; set; }
    }
}
